"""Segment-wise textual dialogue generation (paper Sec. 4.1).

Each dialogue script is built one segment at a time. A segment is a short block of
turns (the paper uses 5-10), generated by the LLM conditioned on a summary of the
preceding segment (speakers, text and sentiment) so that long conversations stay
coherent. Turns are indexed sequentially; the speaker alternates (odd -> S^i,
even -> S^j), matching the odd/even organisation that DADG later relies on. The
LLM's own A/B labels are honoured and validated against this alternation, so a
mislabelled or dropped turn raises rather than silently corrupting the structure.
"""

from __future__ import annotations

import math
from typing import List, Optional, Tuple

from ..config import Config
from ..jsonutil import extract_first_json as _first_json
from ..llm.base import LLMClient
from ..schema import DialogueScript, IdentityDescriptor, Turn
from . import prompts

# Map whatever speaker label the LLM emits onto the canonical codes.
_SPEAKER_ALIASES = {"a": "i", "b": "j", "i": "i", "j": "j", "0": "i", "1": "j"}
# Inverse, for rendering summaries back in the A/B terms the prompts use.
_SPEAKER_LABELS = {"i": "A", "j": "B"}


def _speaker_for_index(k: int) -> str:
    """Paper: odd-indexed turns are expressed by S^i, even-indexed by S^j."""
    return "i" if k % 2 == 1 else "j"


def _map_speaker(label) -> Optional[str]:
    if label is None:
        return None
    return _SPEAKER_ALIASES.get(str(label).strip().lower())


def parse_turns(raw_text: str, start_index: int, limit: Optional[int] = None) -> List[Turn]:
    """Parse an LLM segment response into turns starting at ``start_index``.

    Empty turns are dropped. Each turn's declared speaker is validated against the
    expected alternation; a mismatch raises ``ValueError`` (no silent relabelling).
    """
    items = _first_json(raw_text, "[")
    if not isinstance(items, list):
        raise ValueError("expected a JSON array of turns")
    turns: List[Turn] = []
    offset = 0
    for item in items:
        if limit is not None and offset >= limit:
            break
        if not isinstance(item, dict):
            continue
        text = str(item.get("text", "")).strip()
        if not text:
            continue
        k = start_index + offset
        expected = _speaker_for_index(k)
        declared = _map_speaker(item.get("speaker"))
        if declared is None:
            raise ValueError(f"turn {k} is missing an interpretable speaker label")
        if declared != expected:
            raise ValueError(
                f"dialogue is not strictly alternating at turn {k}: "
                f"LLM labelled it {declared!r}, expected {expected!r}"
            )
        emotion = item.get("emotion")
        emotion = str(emotion).strip() if emotion else None
        turns.append(Turn(index=k, speaker=declared, text=text, emotion=emotion))
        offset += 1
    return turns


def parse_identities(raw_text: str) -> Tuple[IdentityDescriptor, IdentityDescriptor]:
    obj = _first_json(raw_text, "{")
    if not isinstance(obj, dict):
        raise ValueError("expected a JSON object of identity descriptors")
    lowered = {str(key).strip().lower(): str(value).strip() for key, value in obj.items()}
    desc_i = lowered.get("i") or lowered.get("a") or lowered.get("speaker_i") or ""
    desc_j = lowered.get("j") or lowered.get("b") or lowered.get("speaker_j") or ""
    if not desc_i or not desc_j:
        raise ValueError("identity response missing descriptors for i and j")
    return IdentityDescriptor("i", desc_i), IdentityDescriptor("j", desc_j)


def _segment_sizes(total: int, lo: int, hi: int) -> List[int]:
    """Split ``total`` turns into segments, each ideally within ``[lo, hi]``.

    Uses an even split across ceil(total/hi) segments so no segment exceeds ``hi``
    and the final segment is not left below ``lo`` (paper: 5-10 turns per conversation;
    with the default total in [5,10] this yields a single segment).
    Totals that cannot be tiled into [lo, hi] (e.g. total < lo) fall back to the
    closest feasible split.
    """
    if total <= 0:
        return []
    num = max(1, math.ceil(total / hi))
    # Prefer fewer, larger segments if that keeps every segment >= lo without
    # exceeding hi.
    while num > 1 and (total / (num - 1)) <= hi and (total // num) < lo:
        num -= 1
    base, rem = divmod(total, num)
    return [base + 1] * rem + [base] * (num - rem)


def _summarise_tail(turns: List[Turn], max_turns: int = 4) -> str:
    """Summarise the last few turns (speaker, text and sentiment) for conditioning."""
    lines = []
    for t in turns[-max_turns:]:
        line = f"{_SPEAKER_LABELS[t.speaker]}: {t.text}"
        if t.emotion:
            line += f" ({t.emotion})"
        lines.append(line)
    return "\n".join(lines)


def _generate_segment(
    llm: LLMClient,
    cfg: Config,
    system_prompt: str,
    prompt: str,
    prior_turns: List[Turn],
    seg_len: int,
    start_index: int,
) -> List[Turn]:
    last_error: Optional[Exception] = None
    for _ in range(cfg.tdg.max_retries + 1):
        try:
            user_prompt = prompts.segment_user(
                prompt, _summarise_tail(prior_turns), seg_len, start_index
            )
            raw = llm.generate(
                system_prompt,
                user_prompt,
                temperature=cfg.tdg.temperature,
                max_output_tokens=cfg.tdg.max_output_tokens,
            )
            seg = parse_turns(raw, start_index, limit=seg_len)
            if not seg:
                raise ValueError(f"empty dialogue segment at turn {start_index}")
            return seg
        except (ValueError, RuntimeError) as exc:  # parse errors AND transient LLM/API errors
            last_error = exc
    raise ValueError(
        f"failed to generate a valid segment at turn {start_index} "
        f"after {cfg.tdg.max_retries + 1} attempts: {last_error}"
    )


def generate_one_script(prompt: str, llm: LLMClient, cfg: Config, index: int) -> DialogueScript:
    """Generate a single dialogue script with paired identity descriptors."""
    id_raw = llm.generate(
        prompts.IDENTITY_SYSTEM,
        prompts.identity_user(prompt),
        temperature=cfg.tdg.temperature,
        max_output_tokens=cfg.tdg.max_output_tokens,
    )
    identity_i, identity_j = parse_identities(id_raw)
    system_prompt = prompts.dialogue_system(identity_i, identity_j)

    total = cfg.tdg.total_turns
    sizes = _segment_sizes(total, cfg.tdg.segment_min_turns, cfg.tdg.segment_max_turns)
    turns: List[Turn] = []
    for seg_len in sizes:
        turns.extend(
            _generate_segment(llm, cfg, system_prompt, prompt, turns, seg_len, len(turns) + 1)
        )

    # Top up if the LLM under-delivered turns (bounded to avoid runaway calls).
    extra_rounds = 0
    while len(turns) < total and extra_rounds < len(sizes):
        remaining = total - len(turns)
        seg_len = min(cfg.tdg.segment_max_turns, remaining)
        turns.extend(
            _generate_segment(llm, cfg, system_prompt, prompt, turns, seg_len, len(turns) + 1)
        )
        extra_rounds += 1

    return DialogueScript(
        index=index,
        turns=turns,
        identity_i=identity_i,
        identity_j=identity_j,
        prompt=prompt,
    )


def generate_dialogue_scripts(
    prompt: str, llm: LLMClient, cfg: Config, n_scripts: Optional[int] = None
) -> List[DialogueScript]:
    """Generate N dialogue scripts (paper: dg_1 ... dg_N) from one prompt."""
    n = n_scripts if n_scripts is not None else cfg.tdg.num_scripts
    return [generate_one_script(prompt, llm, cfg, idx + 1) for idx in range(n)]
